# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  # Invoke at every 30 minute
  schedule:
  - cron: "0/30 * * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.14

      # Runs a single command using the runners shell
      - name: Execute file
        run: go run cmd/awsome_readme.go

      # Runs a set of commands using the runners shell
      - name: Update readme
        run: |
           git config --global user.email "vtdien96@gmail.com"
           git config --global user.name "vothanhdien"
           git add .
           git commit -m "Updated README.md"
           git push
